# Reproducible Piper TTS image with the lecture voices baked in.
# Linux wheels phonemize correctly (unlike the broken macOS x86_64 wheel), so
# narration is generated by running this container. Build once:
#   docker build -t piper-tts:local -f scripts/audio/piper.Dockerfile scripts/audio
# then `node scripts/audio/build-audio.mjs` (or `just audio`) drives it.
FROM python:3.12-slim
RUN pip install --no-cache-dir piper-tts
# Bake the two narration voices so the image is self-contained and reproducible.
RUN python -m piper.download_voices en_US-amy-medium en_US-ryan-high --download-dir /models
WORKDIR /work
